# Generated by Django 5.0.6 on 2024-05-28 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afinidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Grimorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('numeroHojas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('identificacion', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
                ('afinidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademia.afinidad')),
                ('grimorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademia.grimorio')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField()),
                ('ultimaModificacion', models.DateTimeField(blank=True, null=True)),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademia.estatus')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademia.estudiante')),
            ],
        ),
    ]
