# Generated by Django 5.0.6 on 2024-05-31 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademia', '0002_alter_estudiante_grimorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='afinidad',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='grimorio',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='afinidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='apellido',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='edad',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='grimoro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='identificacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Afinidad',
        ),
        migrations.DeleteModel(
            name='Estatus',
        ),
        migrations.DeleteModel(
            name='Grimorio',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
