# Generated by Django 5.0.6 on 2024-05-31 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademia', '0004_alter_solicitud_afinidad_alter_solicitud_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='creacion',
            field=models.DateTimeField(),
        ),
    ]
