# Generated by Django 5.0.6 on 2024-05-31 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademia', '0005_alter_solicitud_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estatus',
            field=models.CharField(default='creado', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)]),
        ),
    ]
